name: Deploy to Neocities

on: push # triggers every time you run "git push"
  
concurrency: # concurrency stuff. dont worry about it
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # grabs your repository's files
    - name: Deploying to Neocities # deploys them to neocities
      uses: bcomnes/deploy-to-neocities@v1.1.21
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }} # uses your neocities token
        cleanup: true # deletes all files that aren't in your repository. if you don't want this, replace "true" with "false"
        dist_dir: tsvais-place